name: Plugin Compiler

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          path: main
      
      - name: Download PluginLoaderTool
        uses: actions/checkout@v3
        with:
          path: tools
          repository: 'sepluginloader/PluginLoaderTool'

      - name: Space Engineers cache
        uses: actions/cache@v3.2.5
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: se\
          # An explicit key for restoring and saving the cache
          key: seds
          
      - name: NuGet cache
        uses: actions/cache@v3.2.5
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: tools\packages\
          # An explicit key for restoring and saving the cache
          key: loadertool_packages

      # Install SteamCMD
      - name: Setup SteamCMD
        uses: CyberAndrii/setup-steamcmd@v1.1.5
      
        # Install Space Engineers Dedicated Server
      - name: Install Space Engineers
        run: steamcmd +force_install_dir .\se +login anonymous +app_update 298740 +quit
        shell: powershell

      - run: dir -Recurse -Depth 1
      
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Build PluginLoaderTool.exe
        run: |
          msbuild -t:restore -p:RestorePackagesConfig=true tools\PluginLoaderTool.sln
          msbuild -t:Build -p:OutputPath=..\build,Configuration=Release,Platform=x64,TargetFrameworkVersion=v4.8 tools\PluginLoaderTool\PluginLoaderTool.csproj
          
      - name: Run PluginLoaderTools.exe
        run: tools\build\PluginLoaderTool.exe -i main\Plugins --cache compiled_plugins --steamdir se -o plugins.zip
      
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: dir -Recurse -Depth 1
