name: Plugin List Updater

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: 
    - 'Plugins/**'
  
jobs:
  build:
    if: github.repository == 'sepluginloader/PluginHub'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Generate Json
      run: 'python Json/tojson.py Plugins/ plugins.json'
    - name: Push json
      uses: EndBug/add-and-commit@v7
      with:
        message: 'plugin.json updated'
        add: plugins.json
